### ISSUE TITLE
Add step to download .exe and how to use it in cmd or powershell to README

### ISSUE THREAD

**Issue by josefandersson** [NeryK/snowrunner-uwp2steam#1]
Awesome program dude, MANY thanks!

For tech-illiterate guys (which sadly most gamers are...) it would be super cool of you to add a step to the usage, or a Installation subheader that just instructs to those who do not know what these files mean to download the .exe from releases, open cmd or powershell, cd to the directory they downloaded the .exe to and run it with `.\<name>.exe [opts..]`.

A download link in the README at least. 😅

Also maybe change the title of the README to `Snowrunner convert Xbox Game Pass to Steam save` or something so that this may eventually be easier to find in search engines.

Thanks again!

**Comment by NeryK** [comment]
Thanks for the kind words.
I have added more details as you suggested.
